### ISSUE TITLE
Issue With CSS and Fade Animations

### ISSUE THREAD

**Issue by Valley152** [PreMiD/Website#1033] opened 2022-10-25 00:23 UTC
The fade animations seem to not work correctly. When the loading the home page, the CSS animation doesn't start until after everything is loaded. This causes objects to be initially visible, then disappear, and slowly re-appear. On Presence pages, if using an external link to or reloading the page, the items on the page will disappear and won't come back. Two of the videos are mine, one is from someone else on discord.

https://user-images.githubusercontent.com/53654126/197653558-06db7e36-abe5-4579-833f-f18c5ae5262c.mp4

https://user-images.githubusercontent.com/53654126/197653601-467709c9-748d-4edc-b6d0-6a53d6280557.mp4

https://user-images.githubusercontent.com/53654126/197653926-b84d6f00-61be-44fc-9546-343656733651.mp4

**Comment by alexbcberio** [comment] 2022-12-03 14:37
Hello @Valley152, I was not able to reproduce your issue.

I suspect this is due to a adblock/privacy protection extension, on the second video you can see that the extension with a green checkmark its number increases by one. It was supposed to show up a google cookie consent pop-up.

Please, try disabling that extension and check if it works ok after that. Give us also its name, we will try to check what causes the issue and fix it .

**Comment by Valley152** [comment] 2022-12-05 23:37
Hey @alexbcberio,

I have tried disabling my ad blocker, AdGuard, but the website is still broken for me. If anything, the website is even more broken, as when an ad pops up after I click on a presence, I will be met with a blank screen afterwards. I have also tried using a guest window, but the issue appears there as well. I have attached a video of the ad pop-up.

https://user-images.githubusercontent.com/53654126/205767227-fa8e0dd2-4486-4e51-a3a1-971969ebdf68.mp4

**Comment by Valley152** [comment] 2022-12-06 18:50
@alexbcberio, the OS I am using is Windows 10, 22H2 10.0.19045.2251. The browser that I am using is Google Chrome Version 108.0.5359.95 64-bit. The only extension I have that could possibly affect the website, other than my adblocker, is Google Translate.

**Comment by alexbcberio** [comment] 2022-12-08 09:09
Thanks, I will replicate your environment and the check if the issue arises to me too.

**Comment by Bas950** [comment] 2024-01-06 22:57
Fixed in https://github.com/PreMiD/Website/pull/1082

**Closed by Bas950** 2024-01-06 22:57 UTC
Labels: bug
